// tslint:disable
/**
 * api.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import * as url from "url";
import * as isomorphicFetch from "isomorphic-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "http://localhost".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<any>;
}

/**
 *  
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 * 
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = isomorphicFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 * 
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name: "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface ApiDelivery
 */
export interface ApiDelivery {
    /**
     * The date this delivery is for in YYYYMMDD.
     * @type {string}
     * @memberof ApiDelivery
     */
    date?: string;
    /**
     * The timestamp of the delivery.
     * @type {string}
     * @memberof ApiDelivery
     */
    time?: string;
}

/**
 * 
 * @export
 * @interface ApiFetchAllResponse
 */
export interface ApiFetchAllResponse {
    /**
     * 
     * @type {Array&lt;ApiDelivery&gt;}
     * @memberof ApiFetchAllResponse
     */
    delivery?: Array<ApiDelivery>;
}

/**
 * 
 * @export
 * @interface ApiRecordDeliveryResponse
 */
export interface ApiRecordDeliveryResponse {
}


/**
 * ApiServiceApi - fetch parameter creator
 * @export
 */
export const ApiServiceApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchAll(options: any = {}): FetchArgs {
            const path = `/v1/fetch-all`;
            const urlObj = url.parse(path, true);
            const requestOptions = Object.assign({ method: 'GET' }, options);
            const headerParameter = {} as any;
            const queryParameter = {} as any;

            urlObj.query = Object.assign({}, urlObj.query, queryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete urlObj.search;
            requestOptions.headers = Object.assign({}, headerParameter, options.headers);

            return {
                url: url.format(urlObj),
                options: requestOptions,
            };
        },
        /**
         * 
         * @param {string} [date] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recordDelivery(date?: string, options: any = {}): FetchArgs {
            const path = `/v1/record`;
            const urlObj = url.parse(path, true);
            const requestOptions = Object.assign({ method: 'GET' }, options);
            const headerParameter = {} as any;
            const queryParameter = {} as any;

            if (date !== undefined) {
                queryParameter['date'] = date;
            }

            urlObj.query = Object.assign({}, urlObj.query, queryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete urlObj.search;
            requestOptions.headers = Object.assign({}, headerParameter, options.headers);

            return {
                url: url.format(urlObj),
                options: requestOptions,
            };
        },
    }
};

/**
 * ApiServiceApi - functional programming interface
 * @export
 */
export const ApiServiceApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchAll(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<ApiFetchAllResponse> {
            const fetchArgs = ApiServiceApiFetchParamCreator(configuration).fetchAll(options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + fetchArgs.url, fetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @param {string} [date] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recordDelivery(date?: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<ApiRecordDeliveryResponse> {
            const fetchArgs = ApiServiceApiFetchParamCreator(configuration).recordDelivery(date, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + fetchArgs.url, fetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * ApiServiceApi - factory interface
 * @export
 */
export const ApiServiceApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchAll(options?: any) {
            return ApiServiceApiFp(configuration).fetchAll(options)(fetch, basePath);
        },
        /**
         * 
         * @param {string} [date] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recordDelivery(date?: string, options?: any) {
            return ApiServiceApiFp(configuration).recordDelivery(date, options)(fetch, basePath);
        },
    };
};

/**
 * ApiServiceApi - object-oriented interface
 * @export
 * @class ApiServiceApi
 * @extends {BaseAPI}
 */
export class ApiServiceApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiServiceApi
     */
    public fetchAll(options?: any) {
        return ApiServiceApiFp(this.configuration).fetchAll(options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @param {} [date] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiServiceApi
     */
    public recordDelivery(date?: string, options?: any) {
        return ApiServiceApiFp(this.configuration).recordDelivery(date, options)(this.fetch, this.basePath);
    }

}

